general:
  branches:
    ignore:
      - gh-pages

test:
  override:
    - exit 0

deployment:
  production:
    branch: master
    commands:
      - chmod +x ./scripts/deploy.sh
      - ./scripts/deploy.sh
# version: 2

# refrences:
#   ignored-branches: &ignored-branches
#     branches:
#       ignore:
#         - gh-pages

#   cache-options: &cache-options
#     key: package-cache-{{ checksum "package.json" }}

# jobs:
#   build:
#     docker:
#       - image: circleci/node:8
#     steps:
#       - checkout
#       - restore_cache:
#           <<: *cache-options
#       - run:
#           name: npm-install
#           command: npm install

#       - save_cache:
#           <<: *cache-options
#           paths:
#             - ./node_modules

#   deploy:
#     docker:
#       - image: circleci/node:8
#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - "06:f1:64:8a:d6:e8:f2:fc:90:68:f9:4b:3f:34:e5:52"
#       - checkout
#       - restore_cache:
#           <<: *cache-options
#       - run:
#           name: deploy-gh-pages
#           command: ./bin/deploy

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build:
#           filters:
#             <<: *ignored-branches

#       - export:
#           filters:
#             <<: *ignored-branches
#           requires:
#             - build

#       - deploy:
#           filters:
#             branches:
#               only:
#                 - master
#           requires:
#             - export
